### ISSUE TITLE
Unable to add tag files or delete "new tags"

### ISSUE THREAD

**Issue by cmhosale** [APTrust/dart#549]
Hello - on the bag metadata screen there is an "add new tag" button that does not appear to be functioning as intended. I am not able to add a file as a tag file. If I put a filepath into the "tag file" value, I expect that file to get added to the bag as a tag file. I'm confused by the metadata fields that are displayed when I select "add new tag". Tag file, Tag Name, and Value. What is the intended use of those fields? My apologies if I am misunderstanding their intended use. I am running version 2.0.22 on windows.

I am also not able to delete a "new tag" after I add it to the bag metadata screen.

The use case I have is that I would like to add a report file - something like a mediainfo.xml file - as a tag file. This metadata should be a discrete file included as part of the package, but not stored in the data folder. This functionality is allowed by the bagit spec (https://datatracker.ietf.org/doc/html/rfc8493#section-2.2.4). I am unable to do this in DART.

Thank you!

**Comment by diamondap** [comment]
Sorry I didn't respond sooner. I just saw this. When I tested in DART 2.0.22 in Windows just now, this was working. The new tag file and its tag values appear down at the bottom of the screen, just above the Previous and Next buttons. You should see them if you scroll down.

![Screenshot from 2023-07-05 09-51-08](https://github.com/APTrust/dart/assets/225514/dd05307f-824c-4c11-b649-8e7847370361)

You can't actually delete a tag or file once you've added it on the job metadata page. All you can do is clear out its value.

If you plan on regularly adding a custom tag file with custom fields, you can create your own custom BagIt profile. Once you do that, the file and its fields will appear automatically on the metadata page each time you create a bag with your custom profile. Note, however, that DART only supports the BagIt tag file format for now. That's plain text with colon-separated name-value pairs. 

The only way to include XML metadata files at the moment is in the payload.

For info on creating a custom BagIt profile, see the pages on [creating](https://aptrust.github.io/dart-docs/users/bagit/creating/) and [customizing](https://aptrust.github.io/dart-docs/users/bagit/customizing/) profiles. Also, note that you can [import existing profiles](https://aptrust.github.io/dart-docs/users/bagit/importing/) and then modify them, instead of having to create a profile from scratch.

I hope this helps. Let me know if you need more info.

**Comment by cmhosale** [comment]
Hey thanks! I think that I haven't explained my use case clearly and I apologize. I'd like to add an already existing CSV like the attached
[exiftool-tagfile.csv](https://github.com/APTrust/dart/files/11960703/exiftool-tagfile.csv) as a tag file. This CSV contains additional data about the content files in the Data folder. I want the CSV to be part of the bag, but not be included in the bag's Data folder. I have not been able to do this in DART, but it is something that I've done in other bagging software. It is my understanding that this use of tag files is acceptable in the BagIt spec.

**Comment by diamondap** [comment]
Ah. I see what you're saying. You want to be able to package an existing file as a tag file, outside the payload directory. The BagIt spec does indeed allow that.

Unfortunately, DART does not support that at the moment. I'll open a ticket to add that capability as a new feature. I'm not sure when I can get to that, but it won't be in the next few months.

**Comment by diamondap** [comment]
Can you let me know if [Issue #550](https://github.com/APTrust/dart/issues/550) captures your use case? If so, I'll close this issue and keep that new feature ticket open.

**Comment by cmhosale** [comment]
Thank you! Issue #550 accurately captures my use case. I appreciate you
considering adding this functionality.

**Comment by diamondap** [comment]
Thanks. I'll close this, and I hope to get to #550 sometime soon.
