### ISSUE TITLE
What permissions does Aws need?

### ISSUE THREAD

**Issue by kieranjol** [APTrust/dart#556]
I’ve only started experimenting with s3 for DART now as we’ve just used it with donors to package transfers prior to a cloud transfer service or an external drive. 
Is it just putobject or are there more required? I want to enable the minimal amount possible.

**Comment by diamondap** [comment]
These are the permissions we use to allow depositors to upload to a receiving bucket:

s3:ListBucket
s3:ListMultipartUploadParts
s3:ListBucketMultipartUploads
s3:PutObject

The ListBucket operation may not be strictly necessary in your case. We add it because our depositors sometimes want to know what they've uploading to a receiving bucket. 

I'm not 100% sure, but I think it's a good idea to keep ListMultipartUploadParts and ListBucketMultipartUploads. I believe the Minio S3 client inside of DART may use these to figure out which parts of a large, multi-part upload have succeeded and which need to be retried.

**Comment by kieranjol** [comment]
That worked, thank you so much!!!
